[package]
name = "sui-types"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
bcs = "0.1.3"
itertools = "0.10.3"
once_cell = "1.18.0"
rand = "0.7.3"
serde = { version = "1.0.141", features = ["derive"] }
curve25519-dalek = { version = "3", default-features = false, features = ["serde"] }
serde-name = "0.2.1"
sha2 = "0.9.9"
sha3 = "0.10.2"
thiserror = "1.0.31"
tracing = "0.1"
hex = "0.4.3"
serde_bytes = "0.11.6"
serde_json = "1.0.83"
serde_with = "1.14.0"
signature = "1.5.0"
static_assertions = "1.1.0"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
base64ct = { version = "1.5.1", features = ["std", "alloc"] }
zeroize = "1.5.7"
hkdf = "0.12.3"
digest = "0.10.3"
schemars ="0.8.10"
tonic = "0.7"
strum = "^0.24"
strum_macros = "^0.24"
roaring = "0.9.0"
enum_dispatch = "^0.3"

# This version is incompatible with ed25519-dalek
rand_latest = { version = "0.8.5", package = "rand" }

name-variant = { git = "https://github.com/MystenLabs/mysten-infra", rev = "f4aa523d3029bd6a23bead5f04c182f2cfa04c5e" }
typed-store = { git = "https://github.com/MystenLabs/mysten-infra", rev = "f4aa523d3029bd6a23bead5f04c182f2cfa04c5e" }

move-binary-format = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a" }
move-bytecode-utils = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a" }
move-core-types = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a", features = ["address20"] }
move-disassembler = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a" }
move-ir-types = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a" }
move-vm-types = { git = "https://github.com/move-language/move", rev = "79071528524f08b12e9abb84c1094d8e976aa17a" }

narwhal-executor = { git = "https://github.com/MystenLabs/narwhal", rev = "24353f2f1c5df27a8f1b693d78285faf506e36a2", package = "executor" }
narwhal-crypto = { git = "https://github.com/MystenLabs/narwhal", rev = "24353f2f1c5df27a8f1b693d78285faf506e36a2", package = "crypto" }

workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
bincode = "1.3.3"

